### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [SirBecalo/pwp-capstones#1]
### Criteria 1: Valid Python Code
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ Code looks great for the most part! But there are a few issues that were generating errors:
  + The valid way of determining the number of items in a dictionary is using `len()` instead of `.count()` [[x](https://github.com/SirBecalo/pwp-capstones/blob/72af093cf468b2238961b94c0940ad6b4cb5ebf5/final/TomeRater.py#L15)]
  + The variable name here should be `other_user` instead of `other` (Don't forget to check if their `email`s are the same as well) [[x](https://github.com/SirBecalo/pwp-capstones/blob/72af093cf468b2238961b94c0940ad6b4cb5ebf5/final/TomeRater.py#L18)] 
  + You may want to be consistent and use `total` instead of `self.total`. Also, inside your loop, don't forget to check if the rating is `None` before trying to add to `total` [[x](https://github.com/SirBecalo/pwp-capstones/blob/72af093cf468b2238961b94c0940ad6b4cb5ebf5/final/TomeRater.py#L23-L27)] [[x](https://github.com/SirBecalo/pwp-capstones/blob/72af093cf468b2238961b94c0940ad6b4cb5ebf5/final/TomeRater.py#L57-L61)]
  + I believe you meant `Book()` instead of `book()` for creating a new _Book_ object [[x](https://github.com/SirBecalo/pwp-capstones/blob/72af093cf468b2238961b94c0940ad6b4cb5ebf5/final/TomeRater.py#L94)]
  + Since you are using `i` as your looping variable, you should use that instead of `book` here [[x](https://github.com/SirBecalo/pwp-capstones/blob/72af093cf468b2238961b94c0940ad6b4cb5ebf5/final/TomeRater.py#L143-L144)] and `user` here [[x](https://github.com/SirBecalo/pwp-capstones/blob/72af093cf468b2238961b94c0940ad6b4cb5ebf5/final/TomeRater.py#L151-L152)] (as those are not defined) The `.get_average_rating()` method also do not take any arguments.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 2 (Approaches Expectations)
* _Comment(s):_ Code produces most of the required functions and classes, but there are a few issues preventing some parts from obtaining desired results, such as:
  + The `__repr__()` method should `return` a string instead of printing one [[x](https://github.com/SirBecalo/pwp-capstones/blob/72af093cf468b2238961b94c0940ad6b4cb5ebf5/final/TomeRater.py#L14-L15)]
  + In `.add_user()`, you'll want to create a new _User_ object (ie. `User(name, email)`) and add that to your `self.users` dictionary [[x](https://github.com/SirBecalo/pwp-capstones/blob/72af093cf468b2238961b94c0940ad6b4cb5ebf5/final/TomeRater.py#L117-L118)]
  + In `.add_book_to_user()`, since `.read_book()` and `.add_rating()` are instance methods, you'll want to call them on some _User_ and _Book_ object (ie. `self.users[email]` and `book`) instead of the `User` and `Book` class [[x](https://github.com/SirBecalo/pwp-capstones/blob/72af093cf468b2238961b94c0940ad6b4cb5ebf5/final/TomeRater.py#L105-L106)]
  + In `.most_positive_user()`, you'd want to loop through `self.users.values()` in order to loop through the _User_ objects (since the keys are the users' emails). Inside the loop, it should also be `self.posrating = i.get_average_rating()` instead of `self.posrating = self.books[i]` [[x](https://github.com/SirBecalo/pwp-capstones/blob/72af093cf468b2238961b94c0940ad6b4cb5ebf5/final/TomeRater.py#L151-L154)]
 
### Criteria 3: Software Architecture
* _Score Level:_ 4 (Exceeds Expectations) 
* _Comment(s):_ Code is separated into distinct classes and functions each which are invoked for their own purposes.

### Criteria 4: Uses Python Language Features
* _Score Level:_ 4 (Exceeds Expectations) 
* _Comment(s):_ Code uses language features appropriately. If a task can be solved with a Python language feature, it is.
 
### Overall Score: 13/16

Well done on this project, you definitely have a good sense of how to organize and structure your code! Great job implementing most of the required components - there are just a few issues you could take another look at (see above for details)

And as a further challenge, try implementing the rest of the bonus methods in the `Get Creative` section. Have fun! :)

**Comment by SirBecalo** [comment]
thank you.
